;;; call-graph-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from call-graph.el

(autoload 'call-graph "call-graph" "\
Generate `call-graph' for FUNC / func-at-point / func-in-active-rigion.
With prefix argument, discard cached data and re-generate reference data.

(fn &optional FUNC)" t)
(autoload 'cg-add-caller "call-graph" "\
Manually add FUNC at point into `Call-Graph' internal data structure.
This works as a supplement, as `Global' sometimes fail to find caller.

(fn &optional FUNC)" t)
(autoload 'call-graph-mode "call-graph" "\
Major mode for viewing function's `call graph'.
\\{call-graph-mode-map}

(fn)" t)
(register-definition-prefixes "call-graph" '("call-graph-mode-map" "cg-"))


;;; Generated autoloads from cg-support.el

(register-definition-prefixes "cg-support" '("cg-"))

;;; End of scraped data

(provide 'call-graph-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; call-graph-autoloads.el ends here
